config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root to: redirect('/admin')
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :users, skip: [:sessions, :registrations], controllers: {
    confirmations: "users/confirmations"
  }
  authenticate :admin_user do
    mount RailsPerformance::Engine, at: 'rails/performance'
  end
  namespace :internal_api, defaults: { format: "json" } do
    namespace :v1 do
      namespace :users do
        devise_scope :user do
          post "login", to: "sessions#create", as: "login"
          delete "logout", to: "sessions#destroy", as: "logout"
          post "signup", to: "registrations#create", as: "signup"
          post "forgot_password", to: "passwords#create", as: "forgot_password"
          put "reset_password", to: "passwords#update", as: "reset_password"
          post "resend_confirmation_email", to: "confirmations#create", as: "resend_confirmation_email"
        end
      end
      resources :showtimes, only: [:index, :show] do
        member do
          post 'book_now'
          post 'select_seat'
        end
      end
    
      resources :bookings, only: [:index] do
        member do
          get 'invoice'
          get 'cancel'
          get 'versions'
        end
      end

      resources :stripe_payments, only: [:create] do
        collection do
          put 'confirm'
        end
      end

      resources :movies, only: [:index, :show] do
        resources :ratings, only: [:new, :create]
        member do
          post 'rate'
        end
      end

      resources :notifications, only: [:index] do
        collection do
          post 'mark_as_read'
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root 'showtimes#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :movies, only: [:index] do
    resources :ratings, only: [:new, :create]
    member do
      post 'rate'
    end
  end

  resources :showtimes, only: [:index, :show] do
    member do
      post 'book_now'
      post 'select_seat'
    end
  end

  resources :bookings, only: [:index] do
    member do
      get 'invoice'
      get 'cancel'
      get 'versions'
    end
  end

  resources :theaters, only: [:index] do
    resources :ratings, only: [:new, :create]
    member do
      post 'rate'
    end
  end

  resources :events_raws, only: [:index] do
    collection do
      get :filter_options
      get :filter_data_via_odbc
      get :filter_options_via_odbc
    end
  end
end

app/models/showtime.rb
class Showtime < ApplicationRecord
  belongs_to :movie, counter_cache: true
  belongs_to :theater
  belongs_to :screen
  has_many :bookings, dependent: :destroy
  has_many :showtime_seats, dependent: :destroy

  validates :time, presence: true
  validate :time_cannot_be_in_the_past
  validate :check_time_overlap

  after_create :create_showtime_seats

  after_update :check_showtime_seats

  def self.ransackable_attributes(auth_object = nil)
    %w[id movie.title theater.name theater.location screen.name time created_at updated_at bookings.seats]
  end

  def self.ransackable_associations(auth_object = nil)
    ["bookings", "movie", "theater", "screen"]
  end

  def self.filter(params)
    price_range = params[:price_range].present? ? params[:price_range].split('-').map(&:to_i) : nil
    date = params[:date].present? ? Date.parse(params[:date]) : Date.current
  
    filter_showtimes = includes({showtime_seats: :seat_category}, {movie: {avatar_attachment: :blob}}, :theater, :screen).where('DATE(time) = ?', date) if date.present?
    filter_showtimes = filter_showtimes.where(movie_id: params[:movie_id]) if params[:movie_id].present?
    filter_showtimes = filter_showtimes.where(screen_id: params[:screen_id]) if params[:screen_id].present?
    filter_showtimes = filter_showtimes.where("seat_categories.price >= ? AND seat_categories.price <= ?", price_range.first, price_range.last) if price_range.present?
    filter_showtimes = filter_showtimes.where(theater_id: params[:theater_id]) if params[:theater_id].present?
    filter_showtimes.distinct.order(:time)
  end  

  def update_available_seats(selected_seats, booking)
    total_price = 0.0
  
    # Preload seat categories and showtime seats
    seat_categories = SeatCategory.includes(:showtime_seats).where(name: selected_seats.keys, movie: movie, screen: screen, theater: theater)
    showtime_seats = self.showtime_seats.includes(:seat_category).where(seat_category: seat_categories)
  
    ActiveRecord::Base.transaction do
      selected_seats.each do |seat_category_name, seats|
        seat_category = seat_categories.find { |sc| sc.name == seat_category_name }
        showtime_seat = showtime_seats.find { |ss| ss.seat_category == seat_category }
  
        next unless seat_category && showtime_seat
  
        selected_seat_numbers = seats.map { |seat| seat['seat'] }
  
        selected_seats_price = (selected_seat_numbers.size * seat_category.price.to_f).round(2)
        total_price += selected_seats_price
  
        booked_seat = booking.booked_seats.new(seat_category: seat_category, seats: selected_seat_numbers.join(","), price: selected_seats_price)
  
        unless booked_seat.save
          booked_seat.errors.full_messages.each do |error_message|
            booking.errors.add(:base, error_message)
          end
          raise ActiveRecord::RecordInvalid, booking
        end
  
        available_seats = (showtime_seat.seats.split(",") - selected_seat_numbers).join(",")
        unless showtime_seat.update(seats: available_seats)
          showtime_seat.errors.full_messages.each do |error_message|
            booking.errors.add(:base, error_message)
          end
          raise ActiveRecord::RecordInvalid, booking
        end
      end
  
      unless booking.update(total_price: total_price.round(2))
        raise ActiveRecord::RecordInvalid, booking
      end
      
      puts "Updated available seats and booked seats. Total price: #{total_price.round(2)}"
    end
  end 
  
  def end_time
    time + 3.hours # Assuming you have a duration attribute for showtimes
  end

  private

  def is_available_seat_category?
    SeatCategory.find_by(theater: theater, screen: screen, movie: movie).present? 
  end

  def create_showtime_seats
    begin
      unless is_available_seat_category?
        check_showtime_seats
      else
        SeatCategory.where(theater: theater, screen: screen, movie: movie).each{|sc| self.showtime_seats.create!(seat_category_id: sc.id, seats: sc.seats) }
      end
    rescue StandardError => e
      puts "Error in create_showtime_seats: #{e.message}"
    end
  end

  def check_showtime_seats
    begin      
      unless is_available_seat_category? 
        if (seat_category = SeatCategory.create!(
          name: 'Golden',
          price: 250,
          theater: theater,
          screen: screen,
          movie: movie,
          start_num_of_seat: 1,
          end_num_of_seat: 10,
          seats: (1..10).to_a.join(',')
        ))
          self.showtime_seats.create!(seat_category_id: seat_category.id, seats: seat_category.seats)
        end
      end
    rescue StandardError => e
      puts "Error in check_showtime_seats: #{e.message}"
    end
  end
  

  def time_cannot_be_in_the_past
    errors.add(:time, "can't be in the past") if time.present? && time < DateTime.now
  end

  def check_time_overlap
    return unless time.present?
  
    overlapping_showtime = Showtime.where(theater_id: theater_id, screen_id: screen_id)
                        .where("time >= ? AND time <= ?", time - 3.hours, time + 3.hours)
                        .where.not(id: id)
                        .exists?
  
    errors.add(:time, "conflicts with an existing showtime from #{time.strftime('%H:%M')} to #{self.end_time.strftime('%H:%M')} for the same theater and screen") if overlapping_showtime
  end
  
  
end

app/controllers/internal_api/v1/showtimes_controller.rb
# app/controllers/showtimes_controller.rb
module InternalApi::V1
  class ShowtimesController < ApplicationController
    skip_before_action :authenticate_user!, :authenticate_user_using_x_auth_token, only: [:index, :show]

    def index
      movie = params[:movie_id] ? Movie.find(params[:movie_id]) : nil
      
      # @showtimes = Showtime.where('time >= ?', DateTime.current).where(params[:movie_id].present? ? { movie_id: params[:movie_id] } : {}).order(:time)
      RailsPerformance.measure("Showtime listing", "internal_api/v1/showtimes#index") do
        @showtimes = Showtime.filter(params)
      end
      
      # Calculate price ranges
      seat_categories = SeatCategory.where(params[:movie_id].present? ? { movie_id: params[:movie_id] } : {})
      prices = seat_categories.pluck(:price).uniq
      min_price = prices.min
      max_price = prices.max
      step = 50
      price_ranges = []
      if min_price != max_price
        (min_price..max_price).step(step) do |start_price|
          end_price = start_price + step
          end_price = max_price if end_price > max_price
          price_ranges << {value: "#{start_price}-#{end_price}", label: "#{start_price}-#{end_price}"} unless start_price == end_price
        end
      else
        price_ranges << {value: "0-#{max_price}", label: "0-#{max_price}"}
      end

      # Render JSON response
      render json: {
        showtimes: ShowtimeSerializer.new(@showtimes).as_json,
        movie: movie ? MovieSerializer.new(movie).as_json : nil,
        price_ranges: price_ranges,
        theaters: TheaterSerializer.new(Theater.all).as_json,
        screens: ScreenSerializer.new(Screen.all).as_json
      }
    end
  
    def show
      @showtime = Showtime.find(params[:id])
      @theater = Theater.find(params[:theater_id])
      @screen = Screen.find(params[:screen_id])
      @movie = Movie.find(params[:movie_id])
      @showtime_seats = @showtime.showtime_seats
      seat_cat_ids = @showtime_seats.pluck(:seat_category_id).uniq
      @seat_categories = SeatCategory.where(id: seat_cat_ids).order("price DESC")
      @showtime_seats_group_by_sc = @showtime_seats.group_by(&:seat_category_id).transform_values{|val| val.first}
      
      response_data = {
        showtime: @showtime,
        theater: @theater,
        screen: @screen,
        movie: @movie,
        seat_categories: @seat_categories,
        showtime_seats_group_by_sc: @showtime_seats_group_by_sc,
      }
  
      render json: response_data
    end
  
    def select_seat
      selected_seats = params[:selected_seats] || {}
  
      total_price = calculate_total_price(selected_seats.values.flatten)
  
      render json: { total_price: total_price }
    end
  
    def book_now
      showtime = Showtime.find(params[:id])
      selected_seats = params[:selected_seats] || {}
  
      booking = current_user.bookings.create(showtime: showtime)
  
      begin
        showtime.update_available_seats(selected_seats, booking)
        response_data = {
          success: true,
          booking_id: booking.id,
          redirect_to: invoice_booking_path(booking, showtime_id: showtime.id)
        }
        render json: response_data
      rescue ActiveRecord::RecordInvalid => e
        render json: { success: false, error: e.record.errors.full_messages.join(', ') }
      end
    end
  
    private
  
    def calculate_total_price(selected_seats)
      total_price = selected_seats.map { |item| item["price"].to_i }.sum
    end
  end
end

app/controllers/showtimes_controller.rb
# app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController
  def index
    @categories = MovieCategory.includes(movies: :showtimes).all
  end

  def show
    @showtime = Showtime.find(params[:id])
    @theater = Theater.find(params[:theater_id])
    @screen = Screen.find(params[:screen_id])
    @movie = Movie.find(params[:movie_id])
    @seat_categories = SeatCategory.where(screen: @screen, theater: @theater, movie: @movie).order("price DESC")
    @showtime_seats_group_by_sc = ShowtimeSeat.where(showtime: @showtime, seat_category: @seat_categories).group_by(&:seat_category).transform_values{|val| val.first}
    respond_to do |format|
      format.html
      format.json { render json: { available_seats: @showtime.available_seats } }
    end
  end

  def select_seat
    selected_seats = params[:selected_seats] || {}

    total_price = calculate_total_price(selected_seats.values.flatten)

    render json: { total_price: total_price }
  end

  def book_now
    showtime = Showtime.find(params[:id])
    selected_seats = params[:selected_seats] || {}

    booking = current_user.bookings.create(showtime: showtime)

    begin
      showtime.update_available_seats(selected_seats, booking)
      flash[:notice] = "Booking successful. Your booking ID is #{booking.id}."
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Error processing booking: #{e.record.errors.full_messages.join(', ')}"
    end

    respond_to do |format|
      format.json do
        render json: { success: true, booking_id: booking.id, redirect_to: invoice_booking_path(booking, showtime_id: showtime.id) }
      end
    end
  end

  private

  def calculate_total_price(selected_seats)
    total_price = selected_seats.map { |item| item["price"].to_i }.sum
  end
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper
  def category_for_row(row_index)
    alphabet = ('A'..'Z').to_a
    alphabet[row_index % 26]
  end
end

app/views/showtimes/_showtime_tab.html.erb
<!-- app/views/showtimes/_showtime_tab.html.erb -->
<% theaters_and_screens = showtimes.map { |s| [s.theater, s.screen] }.uniq %>

<% theaters_and_screens.group_by { |theater, _screen| theater }.each do |theater, screens| %>
  <div class="theater-container">
    <h2 class="theater-name"><%= theater.name %></h2>
    <p class="theater-location"><%= theater.location %></p> <!-- Add the location here -->
    <div class="col-md-12">
      <% screens.each do |(_theater, screen)| %>
        <% theater_screen_showtimes = showtimes.select { |s| s.theater == theater && s.screen == screen } %>

        <% if theater_screen_showtimes.size > 3 %>
          <div id="carousel<%= "#{theater.name.parameterize}-#{screen.name.parameterize}" %>" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% theater_screen_showtimes.each_slice(3) do |batch| %>
                <div class="carousel-item <%= batch == theater_screen_showtimes.first(3) ? 'active' : '' %>">
                  <h5 class="screen-name"><%= "#{screen.name}" %></h5>
                  <div class="row">
                    <% batch.each do |showtime| %>
                      <div class="col-md-4">
                        <div class="card mb-3" style="height: 100%; border-radius: 15px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                          <img src="<%= url_for(showtime.movie.avatar) if showtime.movie.avatar.attached? %>" class="card-img-top" alt="Movie Poster" style="height: 200px; object-fit: cover; border-top-left-radius: 15px; border-top-right-radius: 15px;">
                          <div class="card-body">
                            <h5 class="card-title"><%= showtime.movie.title %></h5>
                            <p class="card-text"><strong>Date & Time:</strong> <%= showtime.time.strftime('%B %d, %Y %I:%M %p') %></p>
                            <%= link_to 'Book Now', showtime_path(showtime, theater_id: theater.id, screen_id: screen.id, movie_id: showtime.movie_id), class: 'btn btn-primary' %>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>

            <a class="carousel-control-prev" href="#carousel<%= "#{theater.name.parameterize}-#{screen.name.parameterize}" %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel<%= "#{theater.name.parameterize}-#{screen.name.parameterize}" %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <hr class="section-divider">
        <% else %>
          <div>
            <h5 class="screen-name"><%= "#{screen.name}" %></h5>
            <div class="row">
              <% theater_screen_showtimes.each do |showtime| %>
                <div class="col-md-4">
                  <div class="card mb-3" style="height: 100%; border-radius: 15px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                    <img src="<%= url_for(showtime.movie.avatar) if showtime.movie.avatar.attached? %>" class="card-img-top" alt="Movie Poster" style="height: 200px; object-fit: cover; border-top-left-radius: 15px; border-top-right-radius: 15px;">
                    <div class="card-body">
                      <h5 class="card-title"><%= showtime.movie.title %></h5>
                      <p class="card-text"><strong>Date & Time:</strong> <%= showtime.time.strftime('%B %d, %Y %I:%M %p') %></p>
                      <%= link_to 'Book Now', showtime_path(showtime, theater_id: theater.id, screen_id: screen.id, movie_id: showtime.movie_id), class: 'btn btn-primary btn-sm' %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <hr class="section-divider">
      <% end %>
    </div>
  </div>
<% end %>

app/views/showtimes/index.html.erb
<!-- showtimes/index.html.erb -->
<div class="container mt-5">
  <h1 class="display-4">Showtimes</h1>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" id="myTabs">
    <% @categories.each do |category| %>
      <li class="nav-item">
        <a class="nav-link <%= category == @categories.first ? 'active' : '' %>" id="tab-<%= category.name.parameterize %>" data-toggle="tab" href="#<%= category.name.parameterize %>">
          <%= category.name %>
        </a>
      </li>
    <% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content mt-3">
    <% @categories.each do |category| %>
      <div class="tab-pane fade <%= category == @categories.first ? 'show active' : '' %>" id="<%= category.name.parameterize %>">
        <% if category.movies.blank? || category.movies.flat_map(&:showtimes).blank? %>
          <div class="empty-main-content">
            <p class="empty-tab-message">No showtimes available for this category.</p>
          </div>
        <% else %>
          <%= render 'showtime_tab', category: category, showtimes: category.movies.flat_map(&:showtimes) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/showtimes/show.html.erb
<!-- app/views/showtimes/show.html.erb -->
<div class="container mt-5 movie-details-container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="display-4 movie-title"><%= @movie.title %></h1>
      <p class="lead">Theater: <%= @theater.name %></p>
      <p class="lead">Location: <%= @theater.location %></p>
      <p class="lead"><strong>Date & Time:</strong> <%= @showtime.time.strftime('%B %d, %Y %I:%M %p') %></p>

      <h2 class="mt-4">Available Seats</h2>
      <div id="seat-map" class="mt-3">
        <div class="row">
          <div class="col-md-12">
            <% @seat_categories.group_by(&:screen).each do |screen, screen_seat_categories| %>
              <div class="screen mb-3">
                <h4><%= screen.name %></h4>
              </div>
              <% screen_seat_categories.each do |seat_category| %>
                <% showtime_seat = @showtime_seats_group_by_sc[seat_category] %>
              <% theater_seats = seat_category.seats.split(",") %>
                <% seats_per_row = [theater_seats.size, 10].min %>
                <div class="row">
                  <div class="col-md-2">
                    <p><strong><%= seat_category.name %></strong></p>
                  </div>
                  <div class="col-md-10">
                    <% theater_seats.each_slice(seats_per_row) do |row_seats| %>
                      <div class="row">
                        <% row_seats.each do |seat| %>
                          <% seat_available = showtime_seat.nil? || !showtime_seat.seats.split(",").include?(seat.to_s) %>
                          <div class="col-md-1">
                            <%= link_to 'javascript:void(0)', class: "btn #{seat_available ? 'btn-success' : 'btn-outline-success'} m-1 seat-btn", disabled: seat_available, data: { showtime_id: @showtime.id, seat_number: seat, seat_price: seat_category.price, seat_category_name: seat_category.name } do %>
                              <%= seat %>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12 mt-4">
        <div class="card additional-info">
          <div class="card-body text-center">
            <p id="selected-seats-info"></p>
            <p id="total-price-info"><strong>Total Price:</strong> ₹<span id="total-price">0.00</span></p>
          </div>
        </div>
      </div>
      <div class="col-md-12 d-flex justify-content-center align-items-center mt-4">
        <%= link_to 'Back', showtimes_path, class: 'btn btn-primary mr-3' %>
        <%= link_to 'Book Now', 'javascript:void(0)', class: 'btn btn-success', id:"book-now-btn" %>
      </div>
    </div>
  </div>

</div>

<script>
  const selectedSeatsInfo = document.getElementById('selected-seats-info');
  const totalPriceElement = document.getElementById('total-price');

  let selectedSeats = {};
  
  document.querySelectorAll('.seat-btn').forEach(button => {
    button.addEventListener('click', function (event) {
      event.preventDefault();

      const isDisabled = this.hasAttribute('disabled');

      if (!isDisabled) {
        const showtimeId = this.dataset.showtimeId;
        const seatNumber = this.dataset.seatNumber;
        const seatPrice = this.dataset.seatPrice;
        const seatCatName = this.dataset.seatCategoryName;

        if (this.classList.contains('btn-success')) {
          if (selectedSeats[seatCatName]) {
            this.classList.remove('btn-success');
            this.classList.add('btn-outline-success')
            selectedSeats[seatCatName] = selectedSeats[seatCatName].filter(seat => {
              return seat.seat !== seatNumber;
            });
          }
        } else {
          this.classList.remove('btn-outline-success');
          this.classList.add('btn-success');
          if (selectedSeats[seatCatName]) {
            selectedSeats[seatCatName].push({
              seat: seatNumber,
              price: seatPrice,
            })
          } else {
            selectedSeats[seatCatName] = [{
              seat: seatNumber,
              price: seatPrice,
            }];
          }
        }

        const selectedSeatsByCategory = Object.entries(selectedSeats)
          .map(([category, seats]) => {
            const seatNumbers = seats.map(seat => seat.seat).join(',');
            return `${category}: ${seatNumbers}`;
          })
          .join(' ');
        selectedSeatsInfo.textContent = `Selected Seats: ${selectedSeatsByCategory}`;

        const csrfToken = document.querySelector('meta[name="csrf-token"]').content;

        fetch(`/showtimes/${showtimeId}/select_seat`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': csrfToken,
          },
          body: JSON.stringify({ selected_seats: selectedSeats }),
        })
          .then(response => response.json())
          .then(data => {
            totalPriceElement.textContent = data.total_price.toFixed(2);
          })
          .catch(error => console.error('Error:', error));
      } else {
        alert('This seat is not available.');
      }
    });
  });

  document.getElementById('book-now-btn').addEventListener('click', function () {
    bookNow();
  });
  
  function bookNow() {
    const showtimeId = document.querySelector('.seat-btn').dataset.showtimeId;
    const csrfToken = document.querySelector('meta[name="csrf-token"]').content;

    fetch(`/showtimes/${showtimeId}/book_now`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': csrfToken,
      },
      body: JSON.stringify({ selected_seats: selectedSeats }),
    })
    .then(response => response.json())
    .then(data => {
      // Handle the response, e.g., display a success message
      console.log('Booking successful:', data);

      if (data.redirect_to) {
        console.log('Redirecting to:', data.redirect_to);
        // Redirect only after the fetch request is complete
        window.location.href = data.redirect_to;
      } else {
        console.log('No redirection path provided.');
        // Handle other cases or display additional messages
      }
    })
    .catch(error => console.error('Error:', error));
  }
</script>