config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root to: redirect('/admin')
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :users, skip: [:sessions, :registrations], controllers: {
    confirmations: "users/confirmations"
  }
  authenticate :admin_user do
    mount RailsPerformance::Engine, at: 'rails/performance'
  end
  namespace :internal_api, defaults: { format: "json" } do
    namespace :v1 do
      namespace :users do
        devise_scope :user do
          post "login", to: "sessions#create", as: "login"
          delete "logout", to: "sessions#destroy", as: "logout"
          post "signup", to: "registrations#create", as: "signup"
          post "forgot_password", to: "passwords#create", as: "forgot_password"
          put "reset_password", to: "passwords#update", as: "reset_password"
          post "resend_confirmation_email", to: "confirmations#create", as: "resend_confirmation_email"
        end
      end
      resources :showtimes, only: [:index, :show] do
        member do
          post 'book_now'
          post 'select_seat'
        end
      end
    
      resources :bookings, only: [:index] do
        member do
          get 'invoice'
          get 'cancel'
          get 'versions'
        end
      end

      resources :stripe_payments, only: [:create] do
        collection do
          put 'confirm'
        end
      end

      resources :movies, only: [:index, :show] do
        resources :ratings, only: [:new, :create]
        member do
          post 'rate'
        end
      end

      resources :notifications, only: [:index] do
        collection do
          post 'mark_as_read'
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root 'showtimes#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :movies, only: [:index] do
    resources :ratings, only: [:new, :create]
    member do
      post 'rate'
    end
  end

  resources :showtimes, only: [:index, :show] do
    member do
      post 'book_now'
      post 'select_seat'
    end
  end

  resources :bookings, only: [:index] do
    member do
      get 'invoice'
      get 'cancel'
      get 'versions'
    end
  end

  resources :theaters, only: [:index] do
    resources :ratings, only: [:new, :create]
    member do
      post 'rate'
    end
  end

  resources :events_raws, only: [:index] do
    collection do
      get :filter_options
      get :filter_data_via_odbc
      get :filter_options_via_odbc
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Book My Show</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Bootstrap CSS -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <style>
    /* Add your custom styles here */

    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .wrapper {
      flex: 1;
    }

    footer {
      background-color: #343a40;
      color: #fff;
      text-align: center;
      padding: 10px 0;
      width: 100%;
      position: fixed;
      bottom: 0;
    }

    header.navbar {
      background-color: #fff; /* Set your desired background color */
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Optional: Add a shadow for depth */
    }

    @media only screen and (max-width: 767px) {
      header.navbar {
        .navbar-nav {
          text-align: center;
        }

        .navbar-toggler {
          margin: 0 auto;
        }
      }
    }
  </style>
</head>

<body>
  <div class="wrapper">
    <header class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
      <div class="container">
        <%= link_to 'Book My Show', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'My Bookings', bookings_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: "delete" }, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>

    <main class="container mt-4">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>

    <footer>
      <p>&copy; <%= Time.now.year %> Book My Show - All Rights Reserved</p>
    </footer>
  </div>

  <!-- Bootstrap JS (optional) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDF Layout</title>
  <%= wicked_pdf_stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
  <%= wicked_pdf_javascript_include_tag "https://code.jquery.com/jquery-3.3.1.slim.min.js" %>
  <%= wicked_pdf_javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" %>
  <%= wicked_pdf_javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
  <style>
    body {
      font-family: 'Arial', sans-serif;
    }

    .container {
      margin: 50px;
    }

    .invoice-container {
      max-width: 600px;
      margin: 0 auto;
      border: 1px solid #ddd;
      padding: 20px;
      border-radius: 10px;
      background-color: #fff;
    }

    h1 {
      text-align: center;
      color: #333;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: #f2f2f2;
    }
  </style>
</head>
<body class="bg-light">
  <div class="container mt-5">
    <%= yield %>
  </div>
</body>
</html>